language: rust
branches:
  only:
    - master
matrix:
  include:
    - os: linux
      rust: stable
      before_script:
        - rustup component add rustfmt
    - os: linux
      rust: nightly
      script:
        - cargo check --workspace --benches
    - os: linux
      rust: stable
      install:
        - cargo install cross
      script:
        - cross test --target=aarch64-linux-android -p tetsy-util-mem
    - os: osx
      osx_image: xcode11.3
      addons:
        firefox: latest
      rust: stable
  allow_failures:
    - rust: nightly
install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | sh
  - source ~/.nvm/nvm.sh
  - nvm install --lts
  - npm install -g geckodriver@1.19.1 # https://github.com/rustwasm/wasm-bindgen/issues/2261
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
  - which geckodriver
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    cargo fmt -- --check;
    fi
  - cargo check --workspace --tests --benches
  - cargo test --workspace --exclude uint --exclude tetsy-fixed-hash --exclude tetsy-crypto
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
    cd tetsy-contract-address/ && cargo test --features=external_doc && cd ..;
    fi
  - cd vapbloom/ && cargo test --no-default-features --features="rustc-hex" && cargo check --benches && cd ..
  - cd tetsy-fixed-hash/ && cargo test --all-features && cargo test --no-default-features --features="byteorder,rustc-hex" && cd ..
  - cd uint/ && cargo test --all-features && cargo test --no-default-features && cd ..
  - cd tetsy-keccak-hash/ && cargo test --no-default-features && cd ..
  - cd tetsy-plain-hasher/ && cargo test --no-default-features && cargo check --benches && cd ..
  - cd tetsy-bytes/ && cargo test --no-default-features && cd ..
  - cd tetsy-crypto/ && cargo test --all-features && cd ..
  - cd tetsy-util-mem/ && cargo test --features=estimate-heapsize && cd ..
  - cd tetsy-util-mem/ && cargo test --features=jemalloc-global && cd ..
  - cd tetsy-util-mem/ && cargo test --features=mimalloc-global && cd ..
  - cd tetsy-util-mem/ && cargo test --no-default-features --features=dlmalloc-global && cd ..
  - cd tetsy-primitive-types/ && cargo test --all-features && cd ..
  - cd tetsy-primitive-types/ && cargo test --no-default-features --features=serde_no_std && cd ..
  - cd rlp/ && cargo test --no-default-features && cargo check --benches && cd ..
  - cd triehash/ && cargo check --benches && cd ..
  - cd tetsy-kvdb-web/ && wasm-pack test --headless --firefox && cd ..
  - cd vapbloom/ && cargo test --all-features && cd ..
  - cd vapory-types/ && cargo test --all-features && cd ..
